# Generated by Django 3.1.4 on 2021-01-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_user',
            name='name',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='new_user',
            name='user_pass',
            field=models.CharField(default='', max_length=30),
        ),
    ]
