# Generated by Django 3.1.4 on 2021-02-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_question_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to='app/quest'),
        ),
    ]
