# Generated by Django 3.1.4 on 2021-02-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_question_date_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest_id', models.IntegerField(unique=True)),
                ('body', models.TextField(default='')),
                ('rating', models.IntegerField(default=0)),
                ('file', models.ImageField(blank=True, default='', upload_to='app/quest')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
