# Generated by Django 3.1.4 on 2021-02-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210205_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='quest_id',
            field=models.IntegerField(),
        ),
    ]
