# Generated by Django 3.1.4 on 2021-02-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210211_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='name_ans',
            field=models.CharField(default='', max_length=30),
        ),
    ]
